#!/bin/bash -e

source /home/jclark/opt/lscsoft/bayeswave_pipeline-enhancements/etc/bayeswave-user-env.sh

#   IMAGE="/cvmfs/ligo-containers.opensciencegrid.org/james-clark/bayeswave/latest"
#   BASEDIR="${PWD}"
#   SINGULARITY_HOME=${BASEDIR} \
#   SINGULARITYENV_LIGO_DATAFIND_SERVER="datafind.ligo.org:443" \
#       singularity exec \
#       --bind /home --bind /tmp \
#       ${IMAGE} bayeswave_pipe \
#       ${BASEDIR}/pmr_config.ini \
#       --workdir ${BASEDIR}/HLV-wdl200av15ls220-137137-netSNR_10 \
#       --skip-megapy \
#       --osg-jobs --glide-in 

if [ $# != 1 ]; then
    echo "Require an NRHDF5 filename"
    exit 1
fi

waveform=$(echo `basename $1` | sed 's/.h5//g') 
XMLDIR="/home/jclark/Projects/bns-short-injections/sim-inspiral/sim-inspiral-fixed-highfreq-snrs"
JOBNAME="HLV-${waveform}-netSNR_10"
XMLFILE="${XMLDIR}/${JOBNAME}.xml.gz"

bayeswave_pipe \
    pmr_config.ini \
    --workdir ${JOBNAME} \
    -I ${XMLFILE} \
    --skip-megapy \
    --osg-jobs --glide-in 

